# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MashinChi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MashinChi

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]	
   
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    
    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'RNAudio', :path => '../node_modules/react-native-audio'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  end	

  target 'MashinChiTests' do
    inherit! :search_paths
    # Pods for testing
  end


  post_install do |installer|
    installer.pods_project.targets.each do |target|
        
    if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
    end
        
    if target.name == "React"
        target.remove_from_project
    end
  end

end
